kind: pipeline
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      cache_from:
        - "ethicaljobs/aphex:latest"
      repo: ethicaljobs/aphex
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args: [ 'VERSION_TAG=${DRONE_TAG=latest}' ]
      tags:
        - 'latest'
        - '${DRONE_TAG=${DRONE_COMMIT=latest}}'
    when:
      event: tag

  - name: notify-slack
    image: plugins/slack
    failure: ignore
    settings:
      webhook:
        from_secret: slack_webhook
      channel: deployments
    when:
      status: changed
